import { IoIosHeartEmpty } from "react-icons/io";
import { CgProductHunt } from "react-icons/cg";
import { IoBatteryDeadOutline } from "react-icons/io5";

export const productFilterMenu = [
  { id: "01", title: "The Daily 4" },
  { id: "02", title: "New" },
  { id: "03", title: "Best Sellers" },
  { id: "04", title: "Value Packs" },
  { id: "05", title: "Wellblends" },
];

export const menuItems = [
  { label: "Products", category: "products" },
  { label: "Find vitamins for me", category: "findVitamins" },
  { label: "Tips & Resources", category: "tipsResources" },
  { label: "About", category: "about" },
];

export const products = [
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 2,
    favorites: <IoIosHeartEmpty />,
    nameBase: "slip longer",
    nameSubtruc: "",
    productTitle: "WELLBLENDS™",
    cetagory: "best_seller",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 3,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "best_seller",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 4,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "value_pack",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 5,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "value_pack",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 6,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 7,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 8,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "the_daily_4",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
];

export const adverties = [
  {
    id: 1,
    heading: "What Vitamins Should I Take?",
    description:
      "Our guide helps you understand the essential nutrients your body needs and find the right supplements to support your health goals. From multivitamins to targeted minerals, we've got you covered.",
    btnText: "contineu reading",
    image: "/image/adverties01.webp",
  },
  {
    id: 2,
    heading: "Your Daily Dose of Wellness: Introducing The Daily 4™",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties02.webp",
  },
  {
    id: 3,
    heading: "5 Key Immune Support Vitamins and Minerals You May Be Missing",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties03.webp",
  },
  {
    id: 4,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 5,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 6,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 7,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
];

export const companiesLogoAndService = [
  {
    id: 1,
    logo: "/companies-logo/partnership-cplmpanies-logo01.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image01.webp",
    serviceBtn: "our exparties",
  },
  {
    id: 2,
    logo: "/companies-logo/partnership-cplmpanies-logo02.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image02.webp",
    serviceBtn: "Our brands",
  },
  {
    id: 3,
    logo: "/companies-logo/partnership-cplmpanies-logo03.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our histoey",
  },
  {
    id: 4,
    logo: "/companies-logo/partnership-cplmpanies-logo02.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our exparties",
  },
  {
    id: 5,
    logo: "/companies-logo/partnership-cplmpanies-logo03.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our exparties",
  },
];
